export const HOSP = 'https://fw.ybj.beijing.gov.cn/hallEnter/#/search/MedicalOrg'
export const HOSP_INTERNET = 'https://ybj.beijing.gov.cn/2020_zwfw/2020_bmcx/202003/t20200309_1682742.html'
export const HOSP_ACLAZZ = 'https://ybj.beijing.gov.cn/2020_zwfw/2020_bmcx/202002/t20200217_1644108.html'
export const HOSP_FIRST_VISIT = 'https://ybj.beijing.gov.cn/2020_zwfw/2020_bmcx/202004/t20200409_1798868.html'
export const DRAG = 'https://fw.ybj.beijing.gov.cn/drug/druginfo/phoneDrugList'
export const DRAG_DETAIL = 'https://fw.ybj.beijing.gov.cn/drug/druginfo/phoneFingDrugById?id=1'

export const BJ_MEDINS_INFO = 'https://fw.ybj.beijing.gov.cn/hsa-local-prd/api/hsa-pss-pw/web/pw/base/queryFixedMedinsInfo'

export const NHSA_QUERYLOCALOPTINS = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryLocalOptins'
export const NHSA_QUERYFIXEDHOSPITAL = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryFixedHospital'
export const NHSA_QUERYRTALPHACBINFO = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryRtalPhacBInfo'
export const NHSA_QUERYSERVICEFACILITIES = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryServiceFacilities'
export const NHSA_QUERYMEDICALSUPPLIESBYPAGE = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryMedicalSuppliesByPage'
export const NHSA_QUERYDISEASECATALOGBYPAGE = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryDiseaseCatalogByPage'
export const NHSA_QUERYSURGICALCATALOGBYPAGE = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/querySurgicalCatalogByPage'
export const NHSA_QUERYTCMDIAGBYPAGE = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryTcmDiagByPage'
export const NHSA_QUERYDRUGTYPEINFO = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryDrugTypeInfo'
export const NHSA_QUERYWMTCMPATINFOBFROMES = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryWmTcmpatInfoBFromEs'
export const NHSA_QUERYTCMHERBINFOBFROMES = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/queryTcmherbInfoBFromEs'
export const NHSA_QUERYSELFPREPINFOBFROMES = 'https://fuwu.nhsa.gov.cn/ebus/fuwu/api/nthl/api/CommQuery/querySelfprepInfoBFromEs'
